kind: pipeline
type: docker
name: default

steps:
- name: trigger-vm-image-creation
  image: plugins/downstream
  settings:
    server: https://droneci.sect.tu-berlin.de
    token: c4861f4fdf10715f87f45b939a442878
    fork: true
    repositories:
      - FlorianNachtigall/drone-testing
      - enowars/Enowars4DevOps
