---
kind: pipeline
type: docker
name: build

steps:
- name: publish-docker-main-app
  image: plugins/docker
  network_mode: registry-network
  settings:
    context: service
    dockerfile: service/App/Dockerfile
    repo: registry:5000/ringring-service
    registry: registry:5000
    insecure: true
- name: publish-docker-invoices
  image: plugins/docker
  network_mode: registry-network
  settings:
    context: service
    dockerfile: service/InvoiceApp/Dockerfile
    repo: registry:5000/ringring-service-invoices
    registry: registry:5000
    insecure: true
- name: publish-docker-postgres
  image: plugins/docker
  network_mode: registry-network
  settings:
    context: service
    dockerfile: service/Postgres/Dockerfile
    repo: registry:5000/ringring-service-postgres
    registry: registry:5000
    insecure: true
- name: publish-invoices-postgres
  image: plugins/docker
  network_mode: registry-network
  settings:
    context: service
    dockerfile: service/InvoicePostgres/Dockerfile
    repo: registry:5000/invoice-service-postgres
    registry: registry:5000
    insecure: true

---
kind: pipeline
type: docker
name: test

steps:
- name: wait-for-services
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - ./utils/wait-for-services.sh
- name: integration-tests
  image: python
  environment:
    PGPASSWORD: mysecretpassword
    PGHOST: postgres
    INVOICE_SERVICE_HOST: invoices
    RINGRING_SERVICE_HOST: ringring
  commands:
  - pip install --upgrade pip && pip install -r integration-tests/requirements.txt
  - pytest --tb=short -l -m "not no_pipeline_support"

services:
- name: ringring
  image: localhost:5000/ringring-service
  environment:
    PGPASSWORD: mysecretpassword
    PGHOST: postgres
    INVOICE_HOST: invoices
- name: invoices
  image: localhost:5000/ringring-service-invoices
  environment:
    PGPASSWORD: mysecretpassword
    PGHOST: invoices-postgres
- name: postgres
  image: localhost:5000/ringring-service-postgres
  environment:
    POSTGRES_PASSWORD: mysecretpassword
    POSTGRES_USER: ringring
    POSTGRES_DB: service
- name: invoices-postgres
  image: localhost:5000/invoice-service-postgres
  environment:
    POSTGRES_PASSWORD: mysecretpassword
    POSTGRES_USER: ringring
    POSTGRES_DB: invoice


volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock

depends_on:
- build

---
kind: pipeline
type: docker
name: deploy

steps:
- name: publish-service-sources
  image: alpine
  environment:
    SSH_KEY:
      from_secret: github_bot_ssh_key
    ACCESS_TOKEN:
      from_secret: github_bot_access_token
  commands:
    - apk update && apk add curl bash
    - curl -s https://$${ACCESS_TOKEN}@raw.githubusercontent.com/enowars/Enowars4DevOps/master/drone-opennebula/push-services.sh | bash -s ringring

- name: trigger-vm-image-creation
  image: plugins/downstream
  settings:
    server: https://droneci.sect.tu-berlin.de
    token:
      from_secret: trigger_token
    fork: true
    repositories:
      - FlorianNachtigall/drone-testing
      - enowars/Enowars4DevOps

trigger:
  branch:
  - master
  - an_end_to_the_madness
  event:
  - push

depends_on:
- test
