version: '3'

services:
  ringring-checker-backend:
    build: .
    ports:
      - 7355:8000
    environment:
     - MONGO_ENABLED=1
     - MONGO_HOST=buggy-db
     - MONGO_PORT=27017
     - MONGO_USER=enoislove
     - MONGO_PASSWORD=enoislife
  checker-db:
    image: mongo
    volumes:
      - ./checker_db_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: enoislove
      MONGO_INITDB_ROOT_PASSWORD: enoislife